plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.aukilabs.framecamera'
version = '0.1.0'

android {
  namespace "com.aukilabs.framecamera"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    minSdkVersion safeExtGet("minSdkVersion", 26)
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.camera:camera-core:1.4.2"
  implementation "androidx.camera:camera-camera2:1.4.2"
  implementation "androidx.camera:camera-lifecycle:1.4.2"
  implementation "androidx.camera:camera-view:1.4.2"
  implementation "androidx.core:core-ktx:1.15.0"
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
